services:
  - type: web
    name: kikabila
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_SUPABASE_URL
        value: https://mtdnwlpzowmedkelridl.supabase.co
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_P4cKk4WnqcBYHmJ1piSkLw_kq4ZNiOA
