services:
  - type: web
    name: kikabila
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: serve dist -p 3000 -s
    envVars:
      - key: NODE_VERSION
        value: 20