services:
  - type: web
    name: kikabila
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s dist -l 3000
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_SUPABASE_URL
        value: https://mtdnwlpzowmedkelridl.supabase.co
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_P4cKk4WnqcBYHmJ1piSkLw_kq4ZNiOA